# Generated by Django 3.0.2 on 2020-02-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shapefile',
            name='srs_wkt',
            field=models.TextField(),
        ),
    ]
