# Generated by Django 3.0.2 on 2020-02-04 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_shapefile_geom_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shapefile',
            name='geom_json',
        ),
    ]
