# Generated by Django 3.0.2 on 2020-02-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0004_remove_shapefile_geom_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='shapefile',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
