# Generated by Django 3.0.2 on 2020-02-04 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0005_shapefile_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shapefile',
            name='upload',
        ),
    ]
