# Generated by Django 3.0.2 on 2020-02-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0006_remove_shapefile_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='shapefile',
            name='json',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
