# Generated by Django 3.0.2 on 2020-02-05 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0007_shapefile_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shapefile',
            name='json',
        ),
    ]
