# Generated by Django 3.0.2 on 2020-02-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0008_remove_shapefile_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
